### ISSUE TITLE
Cannot find module 'fsevents'

### ISSUE THREAD

**Issue by lemonnm** [opentok/opentok-network-test-js#99]
Hi,

I work with Rails 5.2.0 and use Yarn for manage node_module.

When I run "rake assets:precompile" on linux environnement I have error : 

`Error: Cannot find module 'fsevents' `

No problem on macOs.

Error come from file : `node_modules/chokidar/lib`
"Chokidar" It's a dependency of "Webpack".

Do you have a solution?
Or other solution for use "opentok-network-test-js" without "require" ?

Thnaks,
